services:
  php-fpm:
    hostname: php-fpm
    container_name: php-fpm
    build:
      context: .docker/${DOCKER_IMAGE_SOURCE}/
      dockerfile: php8.Dockerfile
      args:
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
        DEV_IMAGE_TAG: ${DEV_IMAGE_TAG}
        PROD_IMAGE_TAG: ${PROD_IMAGE_TAG}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        DOCKER_USER: ${DOCKER_USER}
    expose:
      - "${PHP_EXTERNAL_PORT}" # "9000"
    command: >
      bash -c "/usr/sbin/entrypoint.sh"
    volumes:
      - ${PHP_DATA_PATH:-php-data}:/var/www
      - /etc/localtime:/etc/localtime:ro # timezone
      - ./.docker/dev/php8/conf.d:/usr/local/etc/php/conf.d
    environment:
      # App
      APP_SECRET: ${APP_SECRET}
      APP_NAME: ${APP_NAME}
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 16s
      timeout: 10s
      retries: 10
      start_period: 11s
    networks:
      - default

volumes:
  php-data:

networks:
  default:
    name: ${DOCKER_NETWORK}
    driver: bridge
